@baseUrl = http://localhost:3000

###
# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "Roger Oliveira",
    "email": "meuemail@gmail.com",
    "password": "123456"
}

###